In [1]:
# Read training and test data files
# https://www.kaggle.com/c/digit-recognizer/data

import pandas as pd
train = pd.read_csv(r"E:/MNIST/train.csv").values
#test  = pd.read_csv(r"E:/MNIST/test.csv").values
print(train.shape)
#print(test.shape)

(42000, 785)
(28000, 784)


In [2]:
# Reshape and normalize training data
trainX = train[:, 1:].reshape(train.shape[0],28, 28, 1).astype( 'float32' )
X_train = trainX / 255.0

y_train = train[:,0]

In [3]:
import matplotlib.pyplot as plt
plt.imshow(X_train[0].reshape(28,28))

In [5]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
y_train = lb.fit_transform(y_train)
print(y_train)

[[0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]


In [6]:
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

Using TensorFlow backend.


In [7]:
# Initialising the CNN
classifier = Sequential()

In [8]:
# Step 1 - Convolution
classifier.add(Conv2D(32, (5, 5), input_shape = (28, 28, 1), activation = 'relu'))

# Step 2 - Pooling
classifier.add(MaxPooling2D(pool_size = (2, 2)))

In [9]:
# Adding a second convolutional layer

classifier.add(Conv2D(32, (3, 3), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))

In [10]:
# Step 3 - Flattening
classifier.add(Flatten())

In [11]:
# Step 4 - Full connection
classifier.add(Dense(units = 128, activation = 'relu'))

classifier.add(Dense(units= 50, activation= 'relu' ))

classifier.add(Dense(units = 10, activation = 'softmax'))

In [12]:
# Compiling the CNN
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [13]:
classifier.fit(X_train, y_train,
          epochs=10,
          batch_size= 100)


Epoch 1/10
42000/42000 [==============================] - 699s 17ms/step - loss: 0.2769 - acc: 0.9139
Epoch 2/10
42000/42000 [==============================] - 722s 17ms/step - loss: 0.0708 - acc: 0.9783
Epoch 3/10
42000/42000 [==============================] - 721s 17ms/step - loss: 0.0486 - acc: 0.9851
Epoch 4/10
42000/42000 [==============================] - 693s 16ms/step - loss: 0.0350 - acc: 0.9887
Epoch 5/10
42000/42000 [==============================] - 693s 16ms/step - loss: 0.0296 - acc: 0.9906
Epoch 6/10
42000/42000 [==============================] - 710s 17ms/step - loss: 0.0219 - acc: 0.9930
Epoch 7/10
42000/42000 [==============================] - 718s 17ms/step - loss: 0.0200 - acc: 0.9935
Epoch 8/10
42000/42000 [==============================] - 767s 18ms/step - loss: 0.0168 - acc: 0.9944
Epoch 9/10
42000/42000 [==============================] - 741s 18ms/step - loss: 0.0139 - acc: 0.9955
Epoch 10/10
42000/42000 [==============================] - 739s 18ms/step - loss: 

In [14]:
classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 24, 24, 32)        832       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 12, 12, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 10, 10, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 5, 5, 32)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 800)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               102528    
_________________________________________________________________
dense_2 (Dense)              (None, 50)                6450      
__________